direct_kinematics:
  ros__parameters:
    joint_names: ['revolute_joint', 'prismatic_z_joint', 'prismatic_x_joint']
    sequence:
      - '[[0.0, 0.0, 0.0], 3.0]'
      - '[[0.2, 0.3, 0.2], 2.0]'
      - '[[0.0, 0.18, 0.1], 2.0]'
      - '[[1.0, 0.18, 0.1], 2.0]'
      - '[[1.0, 0.18, 0.25], 2.0]'
      - '[[1.0, 0.225, 0.25], 2.0]'
      - '[[3.14, 0.1, 0.25], 2.0]'
      - '[[3.14, 0.225, 0.25], 2.0]'
      - '[[3.14, -0.225, 0.25], 2.0]'
      - '[[3.14, -0.2, 0.25], 2.0]'
      - '[[3.14, -0.1, 0.25], 2.0]'
      - '[[3.14, -0.05, 0.25], 2.0]'
      - '[[2.14, -0.05, 0.25], 2.0]'
      - '[[1.0, -0.05, 0.25], 2.0]'
      - '[[0.5, -0.05, 0.25], 2.0]'
      - '[[0.0, 0.0, 0.0], 1.0]'

